# Generated by Django 3.1.1 on 2023-04-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_auto_20230418_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='failed_digitization',
        ),
    ]
