# Generated by Django 3.1.1 on 2023-04-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_delete_failed_digitization'),
    ]

    operations = [
        migrations.CreateModel(
            name='failed_digitization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=10)),
                ('file_name', models.CharField(max_length=100)),
            ],
        ),
    ]
