# Generated by Django 3.1.1 on 2023-05-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_bank_bank_lead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_bank',
            name='lead_id',
            field=models.CharField(max_length=30),
        ),
    ]
