# Generated by Django 3.1.1 on 2023-05-03 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_auto_20230503_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_bank',
            name='deal_id',
        ),
    ]
