# Generated by Django 3.1.1 on 2023-05-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_remove_bank_bank_deal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank_bank',
            old_name='lead_id',
            new_name='lead',
        ),
    ]
